version: "3.8"
services:
  timescaledb:
    # image: timescale/timescaledb:1.7.4-pg12
    image: timescale/timescaledb-postgis:latest-pg12
    container_name: timescaledb
    volumes:
      - postgres-vol:/var/lib/postgresql/data
      # - ./postgres_air/postgres_air_data/postgres_air.sql:/data:cached
    ports:
      - 5432:5432/tcp
      # - " 192.168.150.179/20:5432:5432"
    networks:
      - demo-iot-net
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_DB: demo_iot
    deploy:
      restart_policy:
        condition: on-failure
  grafana:
    image: grafana/grafana:8.2.6
    container_name: grafana
    volumes:
      - grafana-vol3:/var/lib/grafana
    ports:
      - "3000:3000/tcp"
      # - "192.168.150.179/20:3000:3000"
    networks:
      - demo-iot-net
    deploy:
      restart_policy:
        condition: on-failure
    # user: '472'
    environment:
      - UID=admin
      - GID=admin
    user: "${UID}:${GID}"
  pgadmin:
    image: biarms/pgadmin4:4.21
    container_name: pgadmin
    volumes:
      - pgadmin-vol:/pgadmin
    ports:
      - "5050:5050/tcp"
      # - "192.168.150.179/20:5050:5050"
    networks:
      - demo-iot-net
    deploy:
      restart_policy:
        condition: on-failure
    links:
      - "timescaledb:pgsql-server"
volumes:
  postgres-vol:
    driver: local
  grafana-vol3:
    driver: local
  pgadmin-vol:
    driver: local
networks:
  demo-iot-net: